Fix broken generic support
Error before this change:

```
test tests/pass/struct_with_generics.rs ... error
┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
error[E0107]: missing generics for struct `Example`
 --> tests/pass/struct_with_generics.rs:4:8
  |
4 | struct Example<T>
  |        ^^^^^^^ expected 1 generic argument
  |
note: struct defined here, with 1 generic parameter: `T`
 --> tests/pass/struct_with_generics.rs:4:8
  |
4 | struct Example<T>
  |        ^^^^^^^ -
help: add missing generic argument
  |
4 | struct Example<T><T>
  |               +++
┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
```

After this change: It's passing.